---
apiVersion: v1
kind: Secret
metadata:
  name: SECRET_NAME
  namespace: NAMESPACE
type: Opaque
# Secrets generally go like this:
data:
  filename: |-
    BASE64_ENCODED_DATA
# Or use stringData, to have it in plain text locally
stringData:
  netrc: |-
    machine gitlab.com
    login oauth
    password TOKEN
