Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos/8"
  config.vm.synced_folder "FOLDER", "/work"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 8192
    vb.cpus = 4
  end
  config.vm.provision "shell", inline: $script
end

$script = <<-SCRIPT
# Provisioning script
SCRIPT
