---
- hosts: all
  remote_user: rihards
  become: yes
  become_user: root
  become_method: sudo
  vars:
    users: # variable refered to in task with_items
      - rihards
  pre_tasks: # Set as pre_task, to run before everything else
    - name: Add SSH key
      authorized_key:
        user: "{{ item }}" # The item from with_items
        state: present
        key: "{{ lookup('file', '../Secrets/SSH_Keys/key.pub') }}"
      with_items: "{{ users }}"
  tasks:
    - name: Bash command
        shell: pwd
        args:
          chdir: /srv/ # Change directory
          executable: /bin/bash
      # Include a "recipe"
    - include: ./tasks/monitor.yml
      when: ansible_facts['hostname'] is match("elastic.*")
      # when: "elastic" in ansible_facts['hostname']
      # when: ansible_facts['hostname'].startswith('elastic')
    - debug:
        msg: "Message: {{ item }}"
      with_items:
      - 1
      - 2
  roles: # Roles
    - role_name_goes_here
---
# If else
vars:
  # This one should be put in one line, to prevent spaces around the output value
  - disk_uuid_1TB: "{% if ansible_facts['devices']['sdb']['partitions']|length == 2 %}
    {{ ansible_facts['devices']['sdb']['partitions']['sdb5']['uuid'] }}
    {% else %}
    {{ ansible_facts['devices']['sda']['partitions']['sda5']['uuid'] }}
    {% endif %}"
  # This one works great
  - disk_uuid_data: "{{ ansible_facts['devices']['sda']['partitions']['sda1']['uuid']
    if ansible_facts['devices']['sda']['partitions']|length == 3
    else
    ansible_facts['devices']['sdb']['partitions']['sdb1']['uuid'] }}"
tasks:
  - debug: msg="{{ disk_uuid_1TB }}"
  - debug: msg="{{ disk_uuid_data }}"
